## Part 2: Data Cleaning and Validation

This section performs data cleaning and validation using Pandas. Missing values, invalid emails, inconsistent formats, and referential integrity are checked. Cleaned datasets are generated and saved for the next stages of analysis.

### Step 1: Import Required Libraries

In [0]:
# ==========================================
# Import Required Libraries
# ==========================================

import pandas as pd
import random
import re

### Step 2: Load Generated CSV Files

In [0]:
# ==========================================
# Load Raw CSV Files
# ==========================================

customers = pd.read_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/customers.csv"
)

products = pd.read_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/products.csv"
)

orders = pd.read_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/orders.csv"
)

order_items = pd.read_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/order_items.csv"
)

print("All datasets loaded successfully.")

All datasets loaded successfully.

### Step 3 : Check Dataset Information

In [0]:
print("Orders")
orders.info()

print("\nCustomers")
customers.info()

print("\nProducts")
products.info()

print("\nOrder Items")
order_items.info()

Orders
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     700 non-null    object
 1   customer_id  665 non-null    object
 2   order_date   700 non-null    object
 3   status       700 non-null    object
 4   region_code  700 non-null    object
dtypes: object(5)
memory usage: 27.5+ KB

Customers
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        500 non-null    object
 1   customer_name      500 non-null    object
 2   email              500 non-null    object
 3   registration_date  500 non-null    object
 4   customer_type      500 non-null    object
dtypes: object(5)
memory usage: 19.7+ KB

Products
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    object
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   subcategory   500 non-null    object
 4   cost_price    500 non-null    int64
dtypes: int64(1), object(4)
memory usage: 19.7+ KB

Order Items
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           2500 non-null   object
 1   order_id          2500 non-null   object
 2   product_id        2500 non-null   object
 3   quantity          2500 non-null   int64
 4   unit_price        2500 non-null   int64
 5   discount_percent  2500 non-null   int64
dtypes: int64(3), object(3)
memory usage: 117.3+ KB

### Step 4 : Clean Orders Dataset

In [0]:
# ==========================================
# Clean Orders Function
# ==========================================

def clean_orders(df):

    df = df.copy()

    # Convert dates
    df["order_date"] = pd.to_datetime(
        df["order_date"],
        errors="coerce",
        dayfirst=True
    )

    # Replace missing customer IDs
    df["customer_id"] = df["customer_id"].fillna("UNKNOWN")

    return df

In [0]:
orders_clean = clean_orders(orders)

orders_clean.head()

/home/spark-4333b527-940e-4a69-bd10-ae/.ipykernel/336/command-5149272055831882-39392793:10: UserWarning: Parsing dates in %Y-%m-%d %H:%M:%S.%f format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df["order_date"] = pd.to_datetime(

   order_id customer_id                 order_date     status region_code
0  ORD00001    CUST0055 2025-01-19 13:13:20.248216    SHIPPED        EAST
1  ORD00002    CUST0004 2025-05-06 05:17:58.825047  CANCELLED        EAST
2  ORD00003    CUST0431 2024-09-28 14:06:12.044264   RETURNED        WEST
3  ORD00004    CUST0412 2024-09-03 16:38:48.924030  DELIVERED        WEST
4  ORD00005    CUST0172 2025-02-12 18:17:33.284518  CANCELLED       SOUTH

### Step 5: Verify Cleaned Orders

In [0]:
# Check cleaned dataset information
orders_clean.info()


# Save cleaned orders dataset
orders_clean.to_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/orders_clean.csv",
    index=False
)

print("orders_clean.csv saved successfully.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   order_id     700 non-null    object
 1   customer_id  700 non-null    object
 2   order_date   700 non-null    datetime64[ns]
 3   status       700 non-null    object
 4   region_code  700 non-null    object
dtypes: datetime64[ns](1), object(4)
memory usage: 27.5+ KB
orders_clean.csv saved successfully.

### Step 6 : Clean Products Dataset

In [0]:
# ==========================================
# Clean Products Dataset
# ==========================================

def clean_products(df):

    df = df.copy()

    # Remove extra spaces and convert product names to Title Case
    df["product_name"] = (
        df["product_name"]
        .str.strip()
        .str.title()
    )

    return df


# Call the cleaning function
products_clean = clean_products(products)

products_clean.head()

  product_id   product_name  category subcategory  cost_price
0   PROD0001  Commodi Chair      Home       Chair       48785
1   PROD0002       Id Jeans  Clothing       Jeans       14280
2   PROD0003   Nulla Comics     Books      Comics       47586
3   PROD0004     Modi Chair      Home       Chair       12821
4   PROD0005      Nam Table      Home       Table       23750

### Step 7: Verify Product Cleaning

In [0]:
# Check cleaned dataset information
products_clean.info()


# Save cleaned products dataset
products_clean.to_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/products_clean.csv",
    index=False
)

print("products_clean.csv saved successfully.")

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   product_id    500 non-null    object
 1   product_name  500 non-null    object
 2   category      500 non-null    object
 3   subcategory   500 non-null    object
 4   cost_price    500 non-null    int64
dtypes: int64(1), object(4)
memory usage: 19.7+ KB
products_clean.csv saved successfully.

### Step 8 : Validate Customer Emails

In [0]:
# ==========================================
# Validate Customer Emails
# ==========================================

def validate_emails(df):

    # Find emails that do not contain '@'
    invalid = df[
        ~df["email"].str.contains("@", na=False)
    ]

    return invalid


# Call the function
invalid_emails = validate_emails(customers)


# Display invalid email records
invalid_emails

    customer_id          customer_name  ... registration_date customer_type
12     CUST0013             Imaran Dua  ...        2024-09-03       REGULAR
98     CUST0099         Pratyush Sarin  ...        2024-10-02       PREMIUM
114    CUST0115          Utkarsh Chana  ...        2025-08-22           VIP
116    CUST0117        Raagini Dhingra  ...        2024-01-20       REGULAR
156    CUST0157                Kai Rai  ...        2024-09-20           VIP
179    CUST0180          Harshil Varty  ...        2024-05-06       REGULAR
337    CUST0338             Ridhi Shan  ...        2026-04-04           VIP
407    CUST0408  Frederick Padmanabhan  ...        2026-01-19           VIP
420    CUST0421    Krishna Viswanathan  ...        2026-01-15           VIP
446    CUST0447           Anirudh Kari  ...        2023-08-06           VIP

[10 rows x 5 columns]

### Step 9: Check Referential Integrity

In [0]:
# ==========================================
# Check Referential Integrity
# ==========================================

def check_referential_integrity(order_items_df, orders_df):

    invalid_orders = order_items_df[
        ~order_items_df["order_id"].isin(
            orders_df["order_id"]
        )
    ]

    return invalid_orders


# Call the function
invalid_order_items = check_referential_integrity(
    order_items,
    orders
)


# Display invalid order references
invalid_order_items

invalid_order_items.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   item_id           0 non-null      object
 1   order_id          0 non-null      object
 2   product_id        0 non-null      object
 3   quantity          0 non-null      int64
 4   unit_price        0 non-null      int64
 5   discount_percent  0 non-null      int64
dtypes: int64(3), object(3)
memory usage: 0.0+ bytes

### Step 10: Data Quality Summary

In [0]:
print("Orders:", len(orders))
print("Customers:", len(customers))
print("Products:", len(products))
print("Order Items:", len(order_items))

print("\nInvalid Emails:", len(invalid_emails))

print("Missing Customer IDs:",
      orders["customer_id"].isna().sum())

print("Negative Quantity:",
      (order_items["quantity"] < 0).sum())

print("Broken Order References:",
      len(invalid_order_items))

Orders: 700
Customers: 500
Products: 500
Order Items: 2500

Invalid Emails: 10
Missing Customer IDs: 35
Negative Quantity: 75
Broken Order References: 0

In [0]:
# ==========================================
# Save Cleaned CSV Files
# ==========================================

customers.to_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/customers_clean.csv",
    index=False
)

products_clean.to_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/products_clean.csv",
    index=False
)

orders_clean.to_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/orders_clean.csv",
    index=False
)

order_items.to_csv(
    "/Volumes/workspace/default/ecommerce_analytics_system/order_items_clean.csv",
    index=False
)

print("All cleaned files saved successfully!")

All cleaned files saved successfully!